In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

import darts
from darts import TimeSeries
from darts.dataprocessing.transformers import Scaler, MissingValuesFiller
from darts.models import DLinearModel

c:\Users\sonng\anaconda3\envs\tsff_env\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
train_df = pd.read_csv('../../data/electricity/train_df.csv')
test_df = pd.read_csv('../../data/electricity/test_df.csv')
X_train_df = pd.read_csv('../../data/electricity/y_train_df.csv')
X_test_df = pd.read_csv('../../data/electricity/X_test_df.csv')
y_train_df = pd.read_csv('../../data/electricity/y_train_df.csv')
y_test_df = pd.read_csv('../../data/electricity/y_test_df.csv')

In [4]:
value_cols = train_df.drop(columns=['datetime_utc']).columns

In [5]:
train_df['datetime_utc'] = pd.to_datetime(train_df['datetime_utc'])
train_df['datetime_utc'] = train_df['datetime_utc'].dt.tz_localize(None)


In [6]:
train_df

datetime_utc  price_de_lag_336  price_de_avg_24  price_at_lag_24  \
0    2022-10-31 23:00:00            135.71       143.192083           130.59   
1    2022-11-01 00:00:00            140.35       141.425000           119.09   
2    2022-11-01 01:00:00            139.95       138.880833           116.32   
3    2022-11-01 02:00:00            150.30       135.647500           114.60   
4    2022-11-01 03:00:00            149.51       132.467917           115.07   
...                  ...               ...              ...              ...   
8993 2023-11-10 18:00:00            120.89        90.798333           112.41   
8994 2023-11-10 19:00:00            100.05        91.503333            99.15   
8995 2023-11-10 20:00:00             96.84        92.433333            85.54   
8996 2023-11-10 21:00:00             93.70        93.263750            84.04   
8997 2023-11-10 22:00:00             84.60        94.048750            74.36   

      price_at_avg_24  price_fr_lag_24  price_fr_avg_24  load_de_lag_24  \
0          145.302083           136.77       142.511250      48193.0200   
1          144.504167           119.09       140.804167      44770.8675   
2          143.657500           116.32       138.950417      43981.9450   
3          142.480000           114.60       136.477083      43422.0775   
4          141.435417           115.07       134.017500      43581.7450   
...               ...              ...              ...             ...   
8993        95.982917           112.22        90.937500      64363.1600   
8994        96.557083           103.63        91.325000      62330.2025   
8995        97.372083            92.50        91.850000      58638.3150   
8996        98.202500            84.04        92.680417      55156.1275   
8997        98.987500            74.36        93.465417      51880.5625   

      load_de_lag_168  load_at    gen_de  gen_de_lag_168  gen_at   gen_fr  \
0          49161.9775   4868.0  49417.49        50407.76  4079.2  40284.0   
1          48136.9350   4378.0  49446.61        49715.33  4027.1  39246.0   
2          47600.7900   4829.0  48568.35        49051.50  3933.9  39366.5   
3          47753.3075   4773.0  48487.32        49083.27  3766.6  37003.5   
4          49360.8175   4833.0  49072.56        50384.18  3585.8  34949.5   
...               ...      ...       ...             ...     ...      ...   
8993       62435.3950   7798.0  54701.73        60625.63  7268.6  63410.5   
8994       59991.6850   7289.0  51345.73        60074.36  6770.3  61559.0   
8995       56167.5975   6780.0  47738.81        58340.22  6173.9  59780.5   
8996       52589.0625   6568.0  45213.73        56945.46  5898.0  58930.5   
8997       49415.5050   6097.0  42545.78        56195.82  5189.3  57284.0   

       windon_de  solar_de  price_de  
0     16063.7425       0.0     80.65  
1     16839.0400       0.0     76.68  
2     17616.8775       0.0     55.26  
3     17984.3850       0.0     37.00  
4     18902.0375       0.0     38.76  
...          ...       ...       ...  
8993  15818.6625       0.0    123.58  
8994  15185.0900       0.0    112.93  
8995  14189.9350       0.0    105.10  
8996  13123.5375       0.0    103.97  
8997  12409.1350       0.0     93.20  

[8998 rows x 17 columns]

In [7]:
series = TimeSeries.from_dataframe(train_df, time_col='datetime_utc', value_cols=value_cols, freq='H')
train, val = series.split_before(pd.Timestamp('2023-10-09 23:00:00'))

In [8]:
scaler = Scaler()
series_scaled = scaler.fit_transform(train)
# series_scaled = scaler.transform(series)
# train_scaled, val_scaled = series_scaled.split_before(pd.Timestamp('2023-10-09 23:00:00'))

In [9]:
train_scaled, val_scaled = series_scaled.split_before(0.95)

In [10]:
train_scaled

<TimeSeries (DataArray) (datetime_utc: 7819, component: 16, sample: 1)>
array([[[0.54566914],
        [0.39011448],
        [0.54127432],
        ...,
        [0.36925814],
        [0.        ],
        [0.49840774]],

       [[0.54965193],
        [0.38661628],
        [0.53140316],
        ...,
        [0.38731282],
        [0.        ],
        [0.49500004]],

       [[0.54930859],
        [0.38157974],
        [0.5290255 ],
        ...,
...
        ...,
        [0.23736035],
        [0.15149105],
        [0.52102557]],

       [[0.57666458],
        [0.32254345],
        [0.57531695],
        ...,
        [0.20209067],
        [0.04570969],
        [0.54630432]],

       [[0.62660406],
        [0.31309724],
        [0.64803736],
        ...,
        [0.20182118],
        [0.00196726],
        [0.56643291]]])
Coordinates:
  * datetime_utc  (datetime_utc) datetime64[ns] 2022-10-31T23:00:00 ... 2023-...
  * component     (component) object 'price_de_lag_336' ... 'price_de'
Dimensions without coordinates: sample
Attributes:
    static_covariates:  None
    hierarchy:          None

In [11]:
val_scaled

<TimeSeries (DataArray) (datetime_utc: 413, component: 16, sample: 1)>
array([[[0.5970335 ],
        [0.31133619],
        [0.55300813],
        ...,
        [0.22211692],
        [0.        ],
        [0.54372924]],

       [[0.54255328],
        [0.31131886],
        [0.52772079],
        ...,
        [0.24369738],
        [0.        ],
        [0.52754054]],

       [[0.52697402],
        [0.31179975],
        [0.51510287],
        ...,
...
        ...,
        [0.12896544],
        [0.        ],
        [0.53218427]],

       [[0.52374658],
        [0.33630527],
        [0.51187543],
        ...,
        [0.11265179],
        [0.        ],
        [0.52591823]],

       [[0.52717144],
        [0.33736851],
        [0.5073862 ],
        ...,
        [0.13757771],
        [0.        ],
        [0.51845049]]])
Coordinates:
  * datetime_utc  (datetime_utc) datetime64[ns] 2023-09-22T18:00:00 ... 2023-...
  * component     (component) object 'price_de_lag_336' ... 'price_de'
Dimensions without coordinates: sample
Attributes:
    static_covariates:  None
    hierarchy:          None

In [12]:
# model = DLinearModel(input_chunk_length=24*2, output_chunk_length=24, n_epochs=6, batch_size = 128, random_state=42, use_static_covariates=False, shared_weights=True)
# model.fit(train_scaled, val_series=val_scaled)
# 8.714575167647306

In [13]:
def smape_loss(y_true, y_pred):
    """
    Calculate the Symmetric Mean Absolute Percentage Error (SMAPE).

    Args:
    y_true (array): True values.
    y_pred (array): Predicted values.

    Returns:
    float: SMAPE score.
    """
    # Avoid division by zero by adding a small epsilon
    epsilon = np.finfo(np.float64).eps
    denominator = np.maximum(np.abs(y_true) + np.abs(y_pred) + epsilon, 0.5 + epsilon)

    # Calculate SMAPE
    smape_value = 100/len(y_true) * np.sum(2 * np.abs(y_pred - y_true) / denominator)
    return smape_value


In [95]:
model = DLinearModel(input_chunk_length=24*2, output_chunk_length=24, n_epochs=5, batch_size = 32, random_state=658, use_static_covariates=False, shared_weights=True)
model.fit(train_scaled, val_series=val_scaled)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name            | Type             | Params
-----------------------------------------------------
0 | criterion       | MSELoss          | 0     
1 | train_metrics   | MetricCollection | 0     
2 | val_metrics     | MetricCollection | 0     
3 | decomposition   | _SeriesDecomp    | 0     
4 | linear_seasonal | Linear           | 1.2 K 
5 | linear_trend    | Linear           | 1.2 K 
-----------------------------------------------------
2.4 K     Trainable params
0         Non-trainable params
2.4 K     Total params
0.009     Total estimated model params size (MB)


Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Epoch 4: 100%|██████████| 243/243 [00:02<00:00, 82.07it/s, train_loss=0.00464, val_loss=0.00719]

`Trainer.fit` stopped: `max_epochs=5` reached.


Epoch 4: 100%|██████████| 243/243 [00:02<00:00, 82.01it/s, train_loss=0.00464, val_loss=0.00719]


DLinearModel(shared_weights=True, kernel_size=25, const_init=True, use_static_covariates=False, input_chunk_length=48, output_chunk_length=24, n_epochs=5, batch_size=32, random_state=658)

In [96]:
prediction = model.predict(n=24, series=val_scaled)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 100.08it/s]


In [97]:
pred = prediction.all_values()[:,-1]
pred

array([[0.51557466],
       [0.5103645 ],
       [0.50347747],
       [0.50147478],
       [0.50543605],
       [0.513484  ],
       [0.51626449],
       [0.52038847],
       [0.50984944],
       [0.50209767],
       [0.49749422],
       [0.49015215],
       [0.48840703],
       [0.4881625 ],
       [0.49402309],
       [0.50617227],
       [0.52441806],
       [0.5430474 ],
       [0.54927405],
       [0.54235476],
       [0.52098444],
       [0.50270191],
       [0.49079575],
       [0.48229176]])

In [98]:
pred = scaler.inverse_transform(prediction).all_values()[:,-1]
pred

array([[100.64963142],
       [ 94.57974591],
       [ 86.55628676],
       [ 84.22313734],
       [ 88.8380545 ],
       [ 98.21399229],
       [101.45328929],
       [106.25777358],
       [ 93.97969737],
       [ 84.94880618],
       [ 79.58573694],
       [ 71.03216089],
       [ 68.99907715],
       [ 68.71419439],
       [ 75.54183546],
       [ 89.69575659],
       [110.95227911],
       [132.65565088],
       [139.90976077],
       [131.84871562],
       [106.95208473],
       [ 85.65275202],
       [ 71.78195859],
       [ 61.87472761]])

In [99]:
test_df['price_de']

0      87.30
1      85.89
2      85.88
3      83.21
4      82.71
5      85.44
6      86.30
7      88.00
8      92.00
9      94.89
10     91.28
11     90.22
12     87.94
13     87.80
14     91.50
15    102.87
16    115.72
17    127.98
18    135.76
19    124.47
20    113.51
21    102.58
22     92.38
23     87.41
Name: price_de, dtype: float64

In [100]:
pred.reshape(1, -1)[0]

array([100.64963142,  94.57974591,  86.55628676,  84.22313734,
        88.8380545 ,  98.21399229, 101.45328929, 106.25777358,
        93.97969737,  84.94880618,  79.58573694,  71.03216089,
        68.99907715,  68.71419439,  75.54183546,  89.69575659,
       110.95227911, 132.65565088, 139.90976077, 131.84871562,
       106.95208473,  85.65275202,  71.78195859,  61.87472761])

In [101]:
test_df['price_de'].values

array([ 87.3 ,  85.89,  85.88,  83.21,  82.71,  85.44,  86.3 ,  88.  ,
        92.  ,  94.89,  91.28,  90.22,  87.94,  87.8 ,  91.5 , 102.87,
       115.72, 127.98, 135.76, 124.47, 113.51, 102.58,  92.38,  87.41])

In [102]:
smape_loss(pred.reshape(1, -1)[0], test_df['price_de'].values)

13.067280048817972

In [94]:
[8.714, 9.488, 10.319, 9.4155]

[8.714, 9.488, 10.319, 9.4155]

In [61]:
np.sqrt((pred.reshape(1, -1)[0] - test_df['price_de'].values)**2).sum()

343.7851494215009

In [532]:
index_cutoffs = [24*i for i in range(14, -1, -1)]
train_list = [series_scaled[:-idx] if idx != 0 else series_scaled for idx in index_cutoffs]
train_df_list = [train_df.iloc[:-idx] if idx != 0 else train_df for idx in index_cutoffs]
index_ceiling = [x.index.stop for x in train_df_list]
test_df_list = [train_df['price_de'].iloc[idx:idx+24] if idx!=index_ceiling[-1] else test_df['price_de'] for idx in index_ceiling]

y_hat_full = np.empty((0, 1))


In [538]:
for i ,train_slice in enumerate(train_list):

    # train_df_slice['datetime_utc'] = pd.to_datetime(train_df_slice['datetime_utc'])
    # train_df_slice['datetime_utc'] = train_df_slice['datetime_utc'].dt.tz_localize(None)
    # train_df_slice_scaled = scaler.transform(train_df_slice)

    prediction = model.predict(n=24, series=train_slice)

    y_pred = scaler.inverse_transform(prediction).all_values()[:,-1].reshape(1, -1)[0]

    y_true = test_df_list[i].values

    print(y_pred)
    print(y_true)
    print(smape_loss(y_pred, y_true))

    y_hat_full = np.vstack((y_hat_full, y_pred.reshape(-1, 1)))


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]

Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 86.17it/s] 

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]



[ 79.95460616  60.58711892  69.46049308  65.3660894   83.9337757
 115.55191186 136.21219182 139.40134615 115.43744838 103.201958
  79.96332901  71.44381723  57.55390228  49.35652535  86.37631516
 126.65307587 148.65031681 190.09933004 198.73452878 198.23722629
 168.52482074 150.37089783 102.54878887  78.47334208]
[ 93.7   84.6   68.61  64.59  55.    60.51  69.01  66.47  79.9   90.69
  89.5   87.01  69.79  69.86  67.9   73.91  87.   112.02 139.8  148.96
 118.83  90.35  83.51  75.48]
32.4265006748586
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 100.03it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]



[ 76.53556064  63.15492723  82.49543105  91.29508243 113.93120048
 137.50593699 155.61346149 152.20935026 132.2588417  114.01933041
  88.18656705  71.25684114  61.43767124  51.98732605  80.14686731
 111.46596098 130.66695535 161.29972348 165.52534916 155.94693507
 130.77778123 103.98121261  73.30152636  60.2564866 ]
[ 4.748e+01  9.600e-01  2.000e-02 -2.400e-01 -2.800e-01 -3.900e-01
 -3.600e-01 -7.000e-02  1.000e-02  0.000e+00 -2.100e-01 -8.000e-02
 -3.000e-02  6.100e-01  1.003e+01  4.003e+01  7.692e+01  8.390e+01
  7.698e+01  6.737e+01  6.216e+01  5.402e+01  5.194e+01  3.841e+01]
140.24812807433028
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 83.37it/s]

GPU available: True (cuda), used: True



[ 82.96239973  72.00765267  88.87760857  98.14209539 121.52871481
 145.06182681 151.46562181 144.69683547 127.08212698 105.06027093
  80.54463832  67.22612583  62.15966693  61.33228283  89.14479979
 115.69023195 127.70490201 151.8931731  150.07064216 139.5654305
 116.29992184  97.75670749  75.73913745  72.85683349]
[  8.     8.17   8.36  10.02  14.78  25.16  80.29 105.91 111.   103.
  90.    96.17 102.54 114.62 123.98 139.45 144.93 165.84 171.   151.1
 129.02 117.27 113.26  95.4 ]
58.45144587872605


TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 90.95it/s] 

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]



[ 98.44862883  87.786269    95.51049422  94.0069842  109.53986227
 131.01667674 138.88550088 136.06979387 120.31685257 106.50510144
  88.49541412  82.86842499  74.66840765  69.75215599  98.76685075
 126.44233128 138.62081483 164.06732814 162.73909961 154.9044411
 130.68117216 117.68820643  90.47961031  85.72285036]
[ 86.05  79.2   71.96  64.8   61.97  69.77  88.48 107.39 108.02 100.5
  93.   101.95 101.49  97.77 104.97 117.51 135.11 161.81 172.04 152.92
 125.88 115.92 104.92  95.37]
18.083188041251823
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 90.88it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]



[ 81.38447708  71.7761311   75.94131789  76.82432766  89.7407182
 103.69364613 108.38030183 106.28163243  98.76314628  87.43174192
  73.04904652  68.0053387   63.11133377  54.08982927  74.75285124
  95.52428462 104.90846008 125.55433395 127.15599454 122.49677636
 109.7831515   99.62578741  82.18404189  75.80538969]
[65.37 65.58 60.79 60.74 58.94 66.04 78.97 85.56 87.77 69.23 59.   51.4
 47.64 51.99 64.07 80.65 78.97 84.95 79.5  66.57 53.15 39.51 34.17 18.76]
37.27765386835941
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 99.97it/s] 

GPU available: True (cuda), used: True



[ 95.72232737  86.82246413  91.71546289  88.87627052  98.67985071
 111.01410284 114.63559692 112.52972376  96.68022684  81.54961433
  60.99160993  51.69231726  44.39158285  37.04405115  58.32219619
  82.23653374  93.31006228 119.07654675 121.23834944 119.30185999
 106.65497306 102.84433206  87.54298875  85.47940424]
[21.4  16.97 15.38 13.41 14.49 22.52 69.57 75.01 78.32 69.16 60.08 61.43
 60.4  59.36 69.5  76.08 79.43 87.26 97.95 93.84 87.76 75.95 72.27 57.04]
53.36491444715627


TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 100.07it/s]

GPU available: True (cuda), used: True



[ 89.19008238  80.24769562  82.47067741  78.00362723  83.7671149
  88.42646122  85.97213285  77.0734857   62.45642809  44.01733497
  20.32890428   8.69871871   2.68959766  -1.09548861  26.35115382
  57.78627911  76.25714457 104.93110149 112.7528176  114.79666141
 105.81254024 100.30666715  86.43521687  82.72971234]
[15.17 11.47 10.    5.73  9.73 23.6  61.58 89.8  95.02 89.59 82.79 71.36
 61.67 60.71 64.72 69.02 81.95 88.   89.25 88.23 69.07 53.13 45.53 20.63]
90.66682526364991


TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 90.92it/s] 
[ 96.61925403  87.2112995   89.13942878  84.89273167  93.35981616
 104.64554267 107.87113831 102.36018306  89.33882196  77.14021432
  59.34417386  51.47809167  45.84504768  43.16687032  71.16451589
  99.97276605 113.43034295 138.70181845 141.37356429 138.27216152
 121.76700376 108.93115727  86.57562619  80.34949069]
[45.72 32.06 30.   22.01 19.19 15.4  16.13 25.08 25.85 20.   13.95 15.2
 20.   21.14 30.79 42.69 40.   48.76 40.   29.61 12.82 10.4  11.73  7.05]
115.73692277370225


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 100.00it/s]

GPU available: True (cuda), used: True



[  7.04161948  -8.53085112 -13.47065965 -22.59276647 -11.55789712
  -7.44804193  -5.69972921  -0.51460195   3.55687449  -2.59763726
  -9.42941985 -10.54875177 -13.80673306 -20.65182082  -1.01971468
  19.79904664  30.56765094  52.50902338  58.49334711  60.08281452
  61.44961315  50.39804338  37.61931928  31.32962377]
[ 8.71  6.59  5.18  2.98  4.24  7.99  7.29 11.29 15.58 24.02 47.47 48.46
 44.28 29.7  38.15 57.18 63.09 74.95 72.67 59.17 46.48 20.85 15.84  5.71]
137.5944751578033


TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 90.79it/s]
[ 72.76765221  57.18477116  60.10742425  55.52962745  64.43312696
  83.20732427  98.83129045 102.35800234  88.3729591   80.4223179
  62.88396825  57.51304388  50.54235278  40.38279473  58.05237476
  76.08653792  80.49883107 101.5426589  100.2910148   98.39021911
  82.16204034  84.38551711  68.40988035  67.49457358]
[2.7600e+00 1.1000e-01 3.0000e-02 1.4000e-01 4.3000e+00 1.6930e+01
 7.2570e+01 9.5560e+01 9.5930e+01 7.4930e+01 6.0140e+01 5.6290e+01
 5.8050e+01 6.6980e+01 8.0290e+01 1.0008e+02 1.1217e+02 1.3767e+02
 1.5094e+02 1.3952e+02 1.1112e+02 1.0567e+02 9.9080e+01 8.7740e+01]
63.58173447742335


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 86.88it/s] 
[ 81.32690392  71.10835908  73.190899    71.29747814  84.32589517
  99.44652295 112.37622248 112.02212625 100.84565638  91.55190015
  75.10940826  66.13993056  57.8922987   51.64722275  74.92566973
  97.11507698 105.64417127 126.0921743  125.10208126 119.40738582
 102.67967522  88.87395891  65.10727603  56.6039847 ]
[ 78.9   76.3   70.8   68.01  70.25  83.35 101.28 132.89 136.05 114.93
  99.45  89.03  86.21  88.79  97.49 108.07 112.9  136.84 149.38 132.42
 104.72  92.98  88.69  74.17]
17.792849645721194


GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 83.39it/s]

GPU available: True (cuda), used: True



[ 2.47729510e+00 -9.75645824e-01  4.77420017e-03  8.42328420e+00
  3.14969121e+01  4.53450610e+01  5.05162270e+01  5.17489107e+01
  4.88817270e+01  2.92362723e+01  1.02639277e+01 -1.09812954e+00
 -4.76256550e+00 -6.35693782e+00  1.77255438e+01  4.56234004e+01
  6.62140252e+01  8.99813262e+01  9.30502546e+01  8.53523268e+01
  7.47599520e+01  4.82876434e+01  2.62514715e+01  1.33688499e+01]
[ 70.6   74.22  66.73  61.98  66.76  75.01  84.5  107.62 111.47  93.57
  84.76  78.85  75.71  76.08  83.15 105.42 116.81 119.04 127.09 120.95
 109.51  92.85  82.99  67.7 ]
108.99634179919835


TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 86.77it/s]

GPU available: True (cuda), used: True



[ 48.94535117  33.90464943  45.88464426  45.5507433   59.28824287
  80.31798276  94.52041068  99.04130077  84.62369684  72.31654362
  48.37745909  38.39540774  27.68659109  17.62615523  42.5558545
  70.96366717  83.61432887 112.31238714 113.70576842 109.66146592
  87.99194099  84.35667649  62.28369302  57.12345976]
[ 71.93  68.33  70.04  72.8   74.44  83.63 109.61 120.06 121.22 109.69
 100.08  95.    90.16  92.32 100.61 116.61 127.01 131.8  128.58 112.12
  96.01  82.78  84.04  74.36]
41.45046563000844


TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]


Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 90.72it/s] 

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]



[ 85.65785427  75.7444115   77.47038907  73.55820913  81.3700581
  90.32347451 101.29662672 100.8030256   89.94345985  81.71843839
  64.47176404  55.07077761  47.1881093   38.03842457  57.63675144
  78.18874284  86.49887907 106.45522907 107.67045757 104.3179354
  90.74677814  83.87730702  67.73618869  61.4014436 ]
[ 64.1   59.73  53.74  48.36  50.    66.78  84.18 106.66 113.   108.48
  97.51  89.92  84.82  86.98  95.95 111.98 125.   136.1  135.1  123.58
 112.93 105.1  103.97  93.2 ]
34.17398029516401
Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 111.13it/s]
[ 97.64038363  86.2899523   85.61880465  78.71081148  85.30304193
  98.34946497 107.53429816 109.93464196 105.13103687 101.10372485
  90.32871654  86.3289527   80.25439015  72.15900931  93.55438438
 115.409393   122.97880164 143.87330152 144.14746551 140.50326241
 124.89156975 115.1587686   92.22201526  82.51041722]
[ 87.3   85.89  85.88  83.21  82.71  85.44  86.3   88.    92.    94.89
  91.28  90.22  87.94  87.8   91

In [540]:
y_hat_full.shape

(360, 1)

In [547]:
y_hat_df = pd.DataFrame({'y_hat_dlin': y_hat_full[-24*8:].flatten()})
y_hat_df.to_csv('base_models_ts/y_hat_df_dlin_bm7.csv', index=False)